---
title: "Tải dữ liệu OBIS"
#description: |
#  Description
# author:
#   - name: Bùi Tuấn Anh
#     url: https://bui-tuananh.github.io
# date: '2024-08-22'
citation: false  
#preview: ../../img/2024-07-file.png   # apparently no way to change the size displayed via css (ignored) or file (stretched)
output:
  distill::distill_article:
    self_contained: false
    toc: true
    css: ../../styles.css
    df_print: kable_df
bibliography:
  - ../../bibs/bib.bib
draft: false
tags: [R 101] #for search
categories:
  - R 101
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo      = T, 
  message   = F, 
  warning   = F, 
  comment   = NA,
  R.options = list(width = 120),
  cache.rebuild = F,
  cache = T,
  fig.align = 'center',
  fig.asp = .7,
  dev = 'svg',
  dev.args = list(bg = 'transparent')
)

library(tidyverse)
# library(broom)
library(kableExtra)
# library(visibly)
library(glmmTMB)
library(reactable)
library(patchwork)

kable_df <- function(..., digits=2) {
  kable(..., digits=digits) %>% 
    kable_styling(full_width = F)
}

rnd = tidyext::rnd #https://m-clark.github.io/tidyext/ #devtools::install_github('m-clark/tidyext')
theme_set(theme_bw())
```

```{r}
library(robis)
```

```{r}
source(file.path("./_posts/2024-09-03_get-obis", "occurrence temperature matching functions.R"))

source("./occurrence temperature matching functions.R")

```

